Convertir.Fecha <- function(x){
  y <- case_when(
    grepl('\\b(\\d{4})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y%m%d'),
    grepl('\\b(\\d{4})/(0[1-9]|1[0-2])/(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y/%m/%d'),
    grepl('\\b(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y-%m-%d'),
    grepl('\\b(\\d{4}).(0[1-9]|1[0-2]).(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y.%m.%d'),
    grepl('\\b(\\d{4}) (0[1-9]|1[0-2]) (0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y %m %d'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(0[1-9]|1[0-2])(\\d{4})\\b', x) ~ as.Date(x, '%d%m%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(0[1-9]|1[0-2])/(\\d{4})\\b', x) ~ as.Date(x, '%d/%m/%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(0[1-9]|1[0-2])-(\\d{4})\\b', x) ~ as.Date(x, '%d-%m-%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(0[1-9]|1[0-2]).(\\d{4})\\b', x) ~ as.Date(x, '%d.%m.%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (0[1-9]|1[0-2]) (\\d{4})\\b', x) ~ as.Date(x, '%d %m %Y'),
    grepl('\\b(\\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%y%m%d'),
    grepl('\\b(\\d{2})/(0[1-9]|1[0-2])/(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%y/%m/%d'),
    grepl('\\b(\\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%y-%m-%d'),
    grepl('\\b(\\d{2}).(0[1-9]|1[0-2]).(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%y.%m.%d'),
    grepl('\\b(\\d{2}) (0[1-9]|1[0-2]) (0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%y %m %d'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(0[1-9]|1[0-2])(\\d{2})\\b', x) ~ as.Date(x, '%d%m%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(0[1-9]|1[0-2])/(\\d{2})\\b', x) ~ as.Date(x, '%d/%m/%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(0[1-9]|1[0-2])-(\\d{2})\\b', x) ~ as.Date(x, '%d-%m-%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(0[1-9]|1[0-2]).(\\d{2})\\b', x) ~ as.Date(x, '%d.%m.%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (0[1-9]|1[0-2]) (\\d{2})\\b', x) ~ as.Date(x, '%d %m %y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)(\\d{4})\\b', x) ~ as.Date(x, '%d%b%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/(\\d{4})\\b', x) ~ as.Date(x, '%d/%b/%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(\\d{4})\\b', x) ~ as.Date(x, '%d-%b-%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic).(\\d{4})\\b', x) ~ as.Date(x, '%d.%b.%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (\\d{4})\\b', x) ~ as.Date(x, '%d %b %Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)(\\d{2})\\b', x) ~ as.Date(x, '%d%b%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/(\\d{2})\\b', x) ~ as.Date(x, '%d/%b/%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(\\d{2})\\b', x) ~ as.Date(x, '%d-%b-%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic).(\\d{2})\\b', x) ~ as.Date(x, '%d.%b.%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (\\d{2})\\b', x) ~ as.Date(x, '%d %b %y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(\\d{4})\\b', x) ~ as.Date(x, '%d%B%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)/(\\d{4})\\b', x) ~ as.Date(x, '%d/%B/%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)-(\\d{4})\\b', x) ~ as.Date(x, '%d-%B-%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre).(\\d{4})\\b', x) ~ as.Date(x, '%d.%B.%Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) (\\d{4})\\b', x) ~ as.Date(x, '%d %B %Y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(\\d{2})\\b', x) ~ as.Date(x, '%d%B%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)/(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)/(\\d{2})\\b', x) ~ as.Date(x, '%d/%B/%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31)-(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)-(\\d{2})\\b', x) ~ as.Date(x, '%d-%B-%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31).(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre).(\\d{2})\\b', x) ~ as.Date(x, '%d.%B.%y'),
    grepl('\\b(0[1-9]|[12]\\d|30|31) (?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) (\\d{2})\\b', x) ~ as.Date(x, '%d %B %y'),
    grepl('\\b(\\d{4})(0[1-9]|[12]\\d|30|31)(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%Y%d%m'),
    grepl('\\b(\\d{4})/(0[1-9]|[12]\\d|30|31)/(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%Y/%d/%m'),
    grepl('\\b(\\d{4})-(0[1-9]|[12]\\d|30|31)-(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%Y-%d-%m'),
    grepl('\\b(\\d{4}).(0[1-9]|[12]\\d|30|31).(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%Y.%d.%m'),
    grepl('\\b(\\d{4}) (0[1-9]|[12]\\d|30|31) (0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%Y %d %m'),
    grepl('\\b(0[1-9]|1[0-2])(0[1-9]|[12]\\d|30|31)(\\d{4})\\b', x) ~ as.Date(x, '%m%d%Y'),
    grepl('\\b(0[1-9]|1[0-2])/(0[1-9]|[12]\\d|30|31)/(\\d{4})\\b', x) ~ as.Date(x, '%m/%d/%Y'),
    grepl('\\b(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|30|31)-(\\d{4})\\b', x) ~ as.Date(x, '%m-%d-%Y'),
    grepl('\\b(0[1-9]|1[0-2]).(0[1-9]|[12]\\d|30|31).(\\d{4})\\b', x) ~ as.Date(x, '%m.%d.%Y'),
    grepl('\\b(0[1-9]|1[0-2]) (0[1-9]|[12]\\d|30|31) (\\d{4})\\b', x) ~ as.Date(x, '%m %d %Y'),
    grepl('\\b(\\d{2})(0[1-9]|[12]\\d|30|31)(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%y%d%m'),
    grepl('\\b(\\d{2})/(0[1-9]|[12]\\d|30|31)/(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%y/%d/%m'),
    grepl('\\b(\\d{2})-(0[1-9]|[12]\\d|30|31)-(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%y-%d-%m'),
    grepl('\\b(\\d{2}).(0[1-9]|[12]\\d|30|31).(0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%y.%d.%m'),
    grepl('\\b(\\d{2}) (0[1-9]|[12]\\d|30|31) (0[1-9]|1[0-2])\\b', x) ~ as.Date(x, '%y %d %m'),
    grepl('\\b(0[1-9]|1[0-2])(0[1-9]|[12]\\d|30|31)(\\d{2})\\b', x) ~ as.Date(x, '%m%d%y'),
    grepl('\\b(0[1-9]|1[0-2])/(0[1-9]|[12]\\d|30|31)/(\\d{2})\\b', x) ~ as.Date(x, '%m/%d/%y'),
    grepl('\\b(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|30|31)-(\\d{2})\\b', x) ~ as.Date(x, '%m-%d-%y'),
    grepl('\\b(0[1-9]|1[0-2]).(0[1-9]|[12]\\d|30|31).(\\d{2})\\b', x) ~ as.Date(x, '%m.%d.%y'),
    grepl('\\b(0[1-9]|1[0-2]) (0[1-9]|[12]\\d|30|31) (\\d{2})\\b', x) ~ as.Date(x, '%m %d %y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)(0[1-9]|[12]\\d|30|31)(\\d{4})\\b', x) ~ as.Date(x, '%b%d%Y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/(0[1-9]|[12]\\d|30|31)/(\\d{4})\\b', x) ~ as.Date(x, '%b/%d/%Y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(0[1-9]|[12]\\d|30|31)-(\\d{4})\\b', x) ~ as.Date(x, '%b-%d-%Y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic).(0[1-9]|[12]\\d|30|31).(\\d{4})\\b', x) ~ as.Date(x, '%b.%d.%Y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (0[1-9]|[12]\\d|30|31) (\\d{4})\\b', x) ~ as.Date(x, '%b %d %Y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)(0[1-9]|[12]\\d|30|31)(\\d{2})\\b', x) ~ as.Date(x, '%b%d%y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/(0[1-9]|[12]\\d|30|31)/(\\d{2})\\b', x) ~ as.Date(x, '%b/%d/%y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(0[1-9]|[12]\\d|30|31)-(\\d{2})\\b', x) ~ as.Date(x, '%b-%d-%y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic).(0[1-9]|[12]\\d|30|31).(\\d{2})\\b', x) ~ as.Date(x, '%b.%d.%y'),
    grepl('\\b(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (0[1-9]|[12]\\d|30|31) (\\d{2})\\b', x) ~ as.Date(x, '%b %d %y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(0[1-9]|[12]\\d|30|31)(\\d{4})\\b', x) ~ as.Date(x, '%B%d%Y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)/(0[1-9]|[12]\\d|30|31)/(\\d{4})\\b', x) ~ as.Date(x, '%B/%d/%Y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)-(0[1-9]|[12]\\d|30|31)-(\\d{4})\\b', x) ~ as.Date(x, '%B-%d-%Y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre).(0[1-9]|[12]\\d|30|31).(\\d{4})\\b', x) ~ as.Date(x, '%B.%d.%Y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) (0[1-9]|[12]\\d|30|31) (\\d{4})\\b', x) ~ as.Date(x, '%B %d %Y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(0[1-9]|[12]\\d|30|31)(\\d{2})\\b', x) ~ as.Date(x, '%B%d%y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)/(0[1-9]|[12]\\d|30|31)/(\\d{2})\\b', x) ~ as.Date(x, '%B/%d/%y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)-(0[1-9]|[12]\\d|30|31)-(\\d{2})\\b', x) ~ as.Date(x, '%B-%d-%y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre).(0[1-9]|[12]\\d|30|31).(\\d{2})\\b', x) ~ as.Date(x, '%B.%d.%y'),
    grepl('\\b(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) (0[1-9]|[12]\\d|30|31) (\\d{2})\\b', x) ~ as.Date(x, '%B %d %y'),
    grepl('\\b(\\d{4})(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y%b%d'),
    grepl('\\b(\\d{4})/(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y/%b/%d'),
    grepl('\\b(\\d{4})-(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y-%b-%d'),
    grepl('\\b(\\d{4}).(?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic).(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y.%b.%d'),
    grepl('\\b(\\d{4}) (?i:ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y %b %d'),
    grepl('\\b(\\d{4})(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y%B%d'),
    grepl('\\b(\\d{4})/(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)/(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y/%B/%d'),
    grepl('\\b(\\d{4})-(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)-(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y-%B-%d'),
    grepl('\\b(\\d{4}).(?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre).(0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y.%B.%d'),
    grepl('\\b(\\d{4}) (?i:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) (0[1-9]|[12]\\d|30|31)\\b', x) ~ as.Date(x, '%Y %B %d'),
    T ~ as.Date(NA))
}
