library(data.table)
library(tidyverse)
library(DT)
library(shinydashboard)
library(shinyBS)
library(shinythemes)

consumo_empresarial <- readRDS(file = "data/consumo_empresarial.rds")
consumo_individual<-readRDS(file = "data/consumo_individual.rds")
informacion_empresa<-readRDS(file = "data/informacion_empresas.rds")